### ISSUE TITLE
SecurityException ExceptionAndroidDataUtils.getPhoneNumberFromSim

### ISSUE THREAD

**Issue by felixeduardo15** [Lenddo/android-lenddo-data#18]
```
Fatal Exception: java.lang.SecurityException: getLine1Number: Neither user 10198 nor current process has android.permission.READ_PHONE_STATE.
       at android.os.Parcel.readException(Parcel.java:1629)
       at android.os.Parcel.readException(Parcel.java:1582)
       at com.android.internal.telephony.IPhoneSubInfo$Stub$Proxy.getLine1NumberForSubscriber(IPhoneSubInfo.java:701)
       at android.telephony.TelephonyManager.getLine1NumberForSubscriber(TelephonyManager.java:2316)
       at android.telephony.TelephonyManager.getLine1Number(TelephonyManager.java:2262)
       at com.lenddo.data.utils.AndroidDataUtils.getPhoneNumberFromSim(SourceFile:231)
       at com.lenddo.data.utils.AndroidDataUtils.sendPhoneModel(SourceFile:288)
       at com.lenddo.data.SendUserService.performFirstTimeSetup(SourceFile:119)
       at com.lenddo.data.SendUserService$2.onSuccess(SourceFile:88)
       at com.lenddo.data.DataManager$2$1.onSuccess(SourceFile:362)
       at com.lenddo.data.client.LenddoClient2$2.onComplete(SourceFile:182)
       at com.lenddo.data.client.http.LenddoOkHttp$LenddoRequestTask.run(SourceFile:348)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by felixeduardo15** [comment]
HTC Desire 10 lifestyle		
6.0.1
Rooted

**Comment by jom16antonio** [comment]
May I know what is your data SDK current version? Thank you

**Comment by Howard3** [comment]
@felixeduardo15 following up on this.

**Comment by felixeduardo15** [comment]
LenddoSDK

   ```
 compileSdkVersion 24
    buildToolsVersion '24.0.1'

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 22
        multiDexEnabled true
    }
```

LenddoDataSDK
```
compileSdkVersion 24
    buildToolsVersion "24.0.1"

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 18
        versionCode 7
        versionName "2.20.2"
    }
```
@Howard3 @jom16antonio

**Comment by jom16antonio** [comment]
The method getLine1NumberForSubscriber from Telephony Manager causes this error. This happens when the correct permission was not granted. According to the Android documentation, the READ_PHONE_STATE or READ_SMS permissions can be used to allow this method to function. Clearly, this was not the case anymore with Android M. The Data SDK will be updated and handle this issue on the next release (v2.21.0) 
Thank you for reporting this issue.
