### ISSUE TITLE
Unable to start receiver com.lenddo.data.receiver.LocationUpdateAlarmReceiver

### ISSUE THREAD

**Issue by gustavomc** [Lenddo/android-lenddo-data#5]
´´´
Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.lenddo.data.receiver.LocationUpdateAlarmReceiver: android.content.ReceiverCallNotAllowedException: IntentReceiver components are not allowed to register to receive intents
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2251)
       at android.app.ActivityThread.access$1500(ActivityThread.java:138)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1281)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4929)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:798)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:565)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by android.content.ReceiverCallNotAllowedException: IntentReceiver components are not allowed to register to receive intents
       at android.app.ReceiverRestrictedContext.registerReceiver(ContextImpl.java:131)
       at android.app.ReceiverRestrictedContext.registerReceiver(ContextImpl.java:125)
       at com.lenddo.data.utils.DataHelper.getBatteryChargeSingle(SourceFile:413)
       at com.lenddo.data.utils.AndroidDataUtils.addToBatteryChargeArray(SourceFile:699)
       at com.lenddo.data.receiver.LocationUpdateAlarmReceiver.onReceive(SourceFile:36)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2244)
       at android.app.ActivityThread.access$1500(ActivityThread.java:138)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1281)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4929)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:798)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:565)
       at dalvik.system.NativeStart.main(NativeStart.java)
´´´

this happens in devices with android version 4.1.1 & 4.1.2

**Comment by jom16antonio** [comment]
hi @gustavomc, we have traced and replicated the issue. Expect a fix via new release today.

**Comment by gustavomc** [comment]
thanks @jom16antonio i´ll wait

**Comment by jom16antonio** [comment]
please update with the following jar library  
https://github.com/Lenddo/android-lenddo-data/blob/master/lenddodatasdk/libs/lenddodata.jar

**Comment by gustavomc** [comment]
hi @jom16antonio i replaced the .jar library, now im getting this error when i try to run:

Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/lenddo/core/analytics/ActionData.class

**Comment by gustavomc** [comment]
thanks for your help @jom16antonio

**Comment by gustavomc** [comment]
justa a quick question @jom16antonio why was this happening?, and how do you replicated the issue?

**Comment by jom16antonio** [comment]
Hi @gustavomc 

This bug is related to a new data monitoring feature the Battery Charge Status Monitor. This monitor is being registered as a service in the background and is evident due to a Context object passed by a onReceive() callback.  In Android versions older than Kitkat, the context object will result in a ReceiverCallNotAllowedException error. This is an android bug in the older versions and does not happen in newer versions of Android. 

This was replicated via code tracing and debugging as this requires a time parameter, since the battery charge information is recorded on a hourly basis. But, If you have your GPS on and the battery charge has changed an hour after the DataSDK is ran in the background, it might trigger and will be replicated. The error will appear in the background and will not affect any application in the foreground. You will have to monitor the logs to capture this error.

This has been solved by changing the old context object into an application context in the  DataSDK.
`new context = oldContext.getApplicationContext();`
