### ISSUE TITLE
NullPointerException com.lenddo.data.utils.AndroidDataUtils

### ISSUE THREAD

**Issue by felixeduardo15** [Lenddo/android-lenddo-data#9]
This happens in some devices.

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference
       at com.lenddo.data.utils.AndroidDataUtils.getUserSharedPreferences(SourceFile:162)
       at com.lenddo.data.utils.AndroidDataUtils.setClientId(SourceFile:183)
       at com.lenddo.data.DataManager.beginAndroidData(SourceFile:295)
       at 
       at com.lenddo.sdk.utils.UIHelper$1$1$1.onSuccess(SourceFile:191)
       at com.lenddo.sdk.core.LenddoClient2$7.onComplete(SourceFile:314)
       at com.lenddo.sdk.http.LenddoOkHttp$LenddoRequestTask.run(SourceFile:123)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

**Comment by jom16antonio** [comment]
Hi @felixeduardo15 

It seems that you are using both the Lenddo DataSDK and Lenddo Onboarding SDK.
Can you please post the sdk version numbers for both libraries.

Also can you send me an apk that produces the above error? Thanks

Regards,
Joey
jom16antonio@gmail.com

**Comment by felixeduardo15** [comment]
lenddodatasdk: versionCode 9 - versionName "2.9"

can you explain where is the Lenddo Onboarding SDK versionName?

**Comment by jom16antonio** [comment]
Current DataSDK version is 2.17 (to release 2.18 this week)
Current Onboarding SDK version is 1.7

your datasdk is 2.9, please do update to current version.
the sdk version number is usually logged in console. If you could send me an **APK** and **replication step**, I could replicate and investigate the error for you.

**Comment by jom16antonio** [comment]
or simply update to the latest versions of the SDKs that can be downloaded  here at GitHub under the release section. Hopefully the updates and fixes of the new versions will resolve your NPE issue.

**Comment by felixeduardo15** [comment]
jar updated, i'll try it again.

**Comment by jom16antonio** [comment]
hi @felixeduardo15,

How was your update? Was the update able to address the issue? If you have any other inquiries please do post it here and I'll guide you.

Regards,
Joey

**Comment by felixeduardo15** [comment]
@jom16antonio release is today, we updated Lenddo. Now we will wait the result.

**Comment by jom16antonio** [comment]
Hi @felixeduardo15 
We have just released v2.18 of the Data SDK. Please be sure to update to get the latest fixes and updates.

**Comment by felixeduardo15** [comment]
@jom16antonio we upload a new version, but now app crash on this.

DataManager line 600 com.lenddo.data.DataManager.setHourlyAlarm

Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.lenddo.data.receiver.ConnectivityChanged: java.lang.SecurityException: get application info: Neither user 1110118 nor current process has android.permission.INTERACT_ACROSS_USERS.
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2844)
       at android.app.ActivityThread.access$1700(ActivityThread.java:178)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1547)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:204)
       at android.app.ActivityThread.main(ActivityThread.java:5643)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
Caused by java.lang.SecurityException: get application info: Neither user 1110118 nor current process has android.permission.INTERACT_ACROSS_USERS.
       at android.os.Parcel.readException(Parcel.java:1546)
       at android.os.Parcel.readException(Parcel.java:1499)
       at android.app.IAlarmManager$Stub$Proxy.set(IAlarmManager.java:214)
       at android.app.AlarmManager.setImpl(AlarmManager.java:414)
       at android.app.AlarmManager.setRepeating(AlarmManager.java:274)
       at com.lenddo.data.DataManager.setHourlyAlarm(SourceFile:600)
       at com.lenddo.data.DataManager.configureAlarm(SourceFile:576)
       at com.lenddo.data.DataManager.performInitialUpload(SourceFile:328)
       at com.lenddo.data.receiver.ConnectivityChanged.onReceive(SourceFile:49)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2837)
       at android.app.ActivityThread.access$1700(ActivityThread.java:178)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1547)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:204)
       at android.app.ActivityThread.main(ActivityThread.java:5643)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by jom16antonio** [comment]
Hi @felixeduardo15,

Thank you for this report. This is the first time I've seen this kind of error. The Lenddo DataSDK has background service that collects periodical data. It seems that the device that it was running the service has changed/switched users, a new feature that was introduced to Android for Work or it could be the Samsung Knox feature.

You may try to add the permission "android.permission.INTERACT_ACROSS_USERS" in the manifest of **lenddodatasdk** module of your app, and might solve the issue. But I advise against this as we still need to test, replicate and fix this fully on our side. And there might be a risk that Google Play will flag the app. Rest assured this case is **rare** and that we will add support for multiple users in an android device asap.

IF you could provide additional information, such as device type, build, model, android api version, etc. It would be helpful in tracking and replicating this kind of error.

Regards,
Joey
